### ISSUE TITLE
Error "expected *const u32, found *const usize"  when using later version

### ISSUE THREAD

**Issue by curiothinker** [petgraph/fixedbitset#114]
I got this error " self.cells.as_slice().as_ptr()
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected *const u32, found *const usize" when wasm-pack build using fixedbitset="0.5.1" .But when I change to "0.1.9" the compilation is successful. why is this happening and how to use the latest version?

**Comment by james7132** [comment]
Can you post the full error? It's not possible to tell what the exact root cause of the compilation failure from what was provided.
