### ISSUE TITLE
Git tags missing for multiple releaes

### ISSUE THREAD

**Issue by paolobarbolini** [petgraph/fixedbitset#126]
Hi! While scraping tarballs from crates.io I've found the following releases to be missing tags:

* 0.5.6 commit: a3b708be8da35105132d1cbc81d74442913bb9a4
* 0.5.5 commit: c69f0ff1e4acb3de540da57fa518792e245e01ba
* 0.5.4 commit: 70b7a1ff305fb917a3660102ffdbc6e28966af75
* 0.5.3 commit: 0dbd45a4901c175041ec0942fb4fe82a9aa90918
* 0.4.2 commit: da287ee91fb539dc1c12028bf820b7e2c414ed35
* 0.4.1 commit: 72bd94d41f892556b63e8de3b69297fc22197252
* 0.4.0 commit: 5ae6d8c6175acea4ee1f8c704bc9de0122b72d0a

Could the tags for at least recent versions be recouped? The commit ids I've put in the list are from the `.cargo_vcs_info.json` file

**Comment by james7132** [comment]
These should be up now.

**Comment by bluss** [comment]
Thanks for fixing 🙂
