### ISSUE TITLE
Bump minimum rust version

### ISSUE THREAD

**Issue by jrraymond** [petgraph/fixedbitset#26]
Are there features `fixedbitset` would benefit from but cannot use without bumping the minimum rust version?

**Comment by bluss** [comment]
I've added a bug label breaking-change which is a good way to track such changes, and also to save and catch up on them when it's a good time for breaking changes.

**Comment by bluss** [comment]
There are no dependencies or dev-deps even, so we're quite free. Using quickcheck could be good, and then we would be in the "rat race", it requires Rust 1.22. at the moment. I don't have a strong urge for any major jumps.

- Using RangeBounds trait from std would be neat, but that's all the way up at Rust 1.28.

**Comment by bluss** [comment]
@jrraymond I'd propose transferring this crate into the petgraph organization. What do you think? Do you want to join the org, too? (It's entirely optional)

**Comment by jrraymond** [comment]
@bluss I think that's a good idea. I'd like to join the org too.

**Comment by bluss** [comment]
Fixed by #35  - now Rust 1.31.
