### ISSUE TITLE
Implement std::fmt::Binary trait

### ISSUE THREAD

**Issue by mruegenberg** [petgraph/fixedbitset#34]
To get a quick overview of the contents of a set, it would be nice to be able to get a binary display of the set. 
The [Binary](https://doc.rust-lang.org/std/fmt/trait.Binary.html) trait seems perfect for this.

**Comment by bluss** [comment]
Sounds good, but if we make a nice display, we should show it in Debug formatting too.

**Comment by bluss** [comment]
Fixed by #39 (I forgot to instruct to put the fixes text in the description there).
