### ISSUE TITLE
Serialization support

### ISSUE THREAD

**Issue by zhengyi-yang** [petgraph/fixedbitset#40]
Can `fixedbitset` support serialization/deserialization using `Serde`?

**Comment by bluss** [comment]
Yes

**Comment by zhengyi-yang** [comment]
Okay, thanks

**Comment by zhengyi-yang** [comment]
Hi,

I'm using `fixedbitset = "0.3.0"`, but when I want to serialization/deserialization a `FixedBitSet` using `Serde`, it says trait not implemented.

```
the trait `_IMPL_DESERIALIZE_FOR_LabelType::_serde::Deserialize<'_>` is not implemented for `fixedbitset::FixedBitSet`
```

How can I solve that?

Thanks.

**Comment by bluss** [comment]
Hi, sorry for the confusion, all I wanted to say was that fixedbitset *can* support serialization, but it needs to be implemented. That is to say - PR welcome.

**Comment by zhengyi-yang** [comment]
Thanks, I'll open a PR soon.
