### ISSUE TITLE
Comparison to empty set returns false for set with no bits set.

### ISSUE THREAD

**Issue by John-Nagle** [petgraph/fixedbitset#71]
"Eq" is true only if the number of bits in the underlying representation is the same. Comparing a bitset against 
FixedBitSet::new() is not necessarily true for the empty set.

**Comment by John-Nagle** [comment]
Maybe define "is_empty()"

**Comment by jrraymond** [comment]
I see how this could be unintuitive. `is_empty` already exists.
This is the second time someone has raised this issue ( #44 )  so I'll update the docs to make this behavior clear.

**Comment by John-Nagle** [comment]
Thanks.
I'll use .is_empty().
As for equality, I think it should be either logical set equality, or not defined at all. Equality of the underlying representation is not what one expects.

**Comment by jrraymond** [comment]
clarification: `is_empty` already exists but doesn't do what you want. To compare the number of 1s are equal you can use `xs.ones().eq(ys.ones())`

The number of 0s isn't part of the underlying implementation. Its already exposed via other methods. There is more discussion on this in #44.

**Comment by John-Nagle** [comment]
_clarification: is_empty already exists but doesn't do what you want._ 

No, it sure doesn't.

```
pub fn is_empty(&self) -> bool {
        self.len() == 0
}
```
That's "is any storage allocated", not "are there any entries". 

The documentation does not say that. **It needs to be made much, much clearer that "bitset" doesn't work like set theory, so that people are warned away from using it.**

**Comment by jrraymond** [comment]
`FixedBitSet is a simple fixed size set of bits that each can be enabled (1 / true) or disabled (0 / false)` is clear imo. Bitsets in general are not synonymous with sets of non-negative integers. 

Suggestions welcome, snark not appreciated 🤷
