### ISSUE TITLE
Return old values in `set` (and potentially other methods)

### ISSUE THREAD

**Issue by SUPERCILEX** [petgraph/fixedbitset#75]
Potential performance optimization for a pattern like this:

```rust
if !received[id] {
  received[id] = true;
  // Do other stuff
}

// Could be this instead
if !received.set(id, true) {
  // Do other stuff
}
```

It would need some benchmarking to make sure the bounds checking and division is actually slow enough to warrant a memory read on every set call.

**Comment by james7132** [comment]
`FixedBitset::put` exists now which does exactly this.
