### ISSUE TITLE
`remove()` method to disable a bit

### ISSUE THREAD

**Issue by your-diary** [petgraph/fixedbitset#81]
I'm new to `FixedBitSet`, but what is the most idiomatic way to disable a bit?

I'm looking for a simple method like `HashSet::remove()`.

Do I have to use `FixedBitSet::set(i, false)`? (Is there any technical reason why `remove()` is not implemented?)

**Comment by jrraymond** [comment]
Use `FixedBitSet::set(i, false)`. There isn't `remove` because conceptually you can think of `FixedBitSet::set(i, false)` as "setting the bit at index `i` to `0`" instead of "removing the int `i` from the set".

**Comment by your-diary** [comment]
Thank you.

> *conceptually you can think of FixedBitSet::set(i, false) as "setting the bit at index i to 0" instead of "removing the int i from the set".*

I see. So, similarly should I use `set(i, true)` instead of `insert()`? Is there any difference between them?

**Comment by jrraymond** [comment]
It's up to you which one to use, there is no difference between them.
