### ISSUE TITLE
Maintainership of this crate

### ISSUE THREAD

**Issue by james7132** [petgraph/fixedbitset#83]
There's currently multiple open PRs ranging from 2016 to midway through this year that have remained unmerged, and multiple issues in the same timescale without any response.

Is it possible to expand the maintainer group of this library? There are many operations that could be optimized for, benchmarks to expand coverage, etc.

This crate currently has 33 million all time downloads on crates.io, nearly 2x the next competitor in this niche, and is being actively used in multiple high profile projects like `petgraph` and `bevy_ecs`. It'd be a shame to need to fork this library to provide the Rust ecosystem with these improvements.

**Comment by jrraymond** [comment]
@james7132 would you like to become a maintainer?

**Comment by james7132** [comment]
Would be more than happy to help maintain the crate.

**Comment by alice-i-cecile** [comment]
@james7132 this can likely be resolved.

**Comment by james7132** [comment]
I think I still need access to publish new versions of the crate to crates.io.

**Comment by james7132** [comment]
This has been done.
