### ISSUE TITLE
Differences in benchmarks after moving benches to the separate file

### ISSUE THREAD

**Issue by fuine** [petgraph/fixedbitset#9]
I'm implementing iterator over unset bits, but i noticed that benches for `ones` are significantly worse after they are moved to the separate file. Take a look:
```
$  git checkout e92c5eca22b62b0eb36b721a9b11739b83390cfd
$ cargo bench --features=unstable
test bench::bench_iter_ones_all_ones                      ... bench:   1,095,463 ns/iter (+/- 92,484)
test bench::bench_iter_ones_all_zeros                     ... bench:      29,367 ns/iter (+/- 1,309)
test bench::bench_iter_ones_using_contains_all_ones       ... bench:     940,732 ns/iter (+/- 38,425)
test bench::bench_iter_ones_using_contains_all_zeros      ... bench:     784,732 ns/iter (+/- 50,771)
test bench::bench_iter_ones_using_slice_directly_all_ones ... bench:     696,833 ns/iter (+/- 123,018)
test bench::bench_iter_ones_using_slice_directly_all_zero ... bench:      30,110 ns/iter (+/- 10,471)

$ git checkout 51c1e7414ecfc21f6f81968ef2cd11b16d059dc8
$ cargo bench
test bench_iter_ones_all_ones                      ... bench:   3,419,658 ns/iter (+/- 665,823)
test bench_iter_ones_all_zeros                     ... bench:      63,210 ns/iter (+/- 4,960)
test bench_iter_ones_using_contains_all_ones       ... bench:     950,322 ns/iter (+/- 49,482)
test bench_iter_ones_using_contains_all_zeros      ... bench:     822,978 ns/iter (+/- 109,732)
test bench_iter_ones_using_slice_directly_all_ones ... bench:     773,788 ns/iter (+/- 207,150)
test bench_iter_ones_using_slice_directly_all_zero ... bench:      38,948 ns/iter (+/- 2,617)
```
It looks as if something is not getting inlined ? Notably, even if benches are in the same file on my machine bench for `ones` is significantly worse than using slice directly. Can you comment on that @mneumann ?

My setup is `rustc 1.15.0-nightly (daf8c1dfc 2016-12-05)`, running on `Intel Core i5-3320M CPU @ 3.3GHz`. I can provide benches for a machine with Intel Xeon inside if need be.

**Comment by fuine** [comment]
After taking a look at the sources it looks like `next` method of the iterator needs an `#[inline]`, i will change that in the upcoming PR for `zeros` iterator. I would still like to know why is the iterator version slower than implementation over raw slices.

**Comment by bluss** [comment]
If you need this crate for an urgent project I recommend sticking to a local version of it. Profiling will show non-inlined functions readily.

Here's a guess why the method that iterates is more efficient: https://medium.com/@veedrac/rust-is-slow-and-i-am-the-cure-32facc0fdcb#.rbo3c3dp3

It's related to the segmented iteration, and the problem of trying to reconstruct nested loops from a segmented iterator's .next(). `fold` (or [`fold_ok`](https://internals.rust-lang.org/t/pre-rfc-fold-ok-is-composable-internal-iteration/4434)) can be implemented like `iter_ones_using_slice_directly` even for the ones/zeros iterators.

**Comment by bluss** [comment]
Just whatever you do, don't take the blog's title at face value. But it has something to say.

**Comment by fuine** [comment]
Yea, it was just a thing that i noticed while running benchmarks. I will obviously submit a non-profiled version, as i don't need the blazing speed for my use case. I am willing to profile and possibly optimize these iterators once i will have more free time on my hands.

**Comment by jrraymond** [comment]
The difference in cargo 1.58.0-nightly is within the margin of measurement error.

The benchmarks from the same file:
```
test bench_insert_range                            ... bench:       2,787 ns/iter (+/- 251)
test bench_insert_range_using_loop                 ... bench:   2,118,929 ns/iter (+/- 92,808)
test bench_iter_ones_all_ones                      ... bench:     808,933 ns/iter (+/- 31,158)
test bench_iter_ones_all_zeros                     ... bench:       9,817 ns/iter (+/- 413)
test bench_iter_ones_using_contains_all_ones       ... bench:     526,285 ns/iter (+/- 13,027)
test bench_iter_ones_using_contains_all_zeros      ... bench:     523,800 ns/iter (+/- 7,628)
test bench_iter_ones_using_slice_directly_all_ones ... bench:     370,023 ns/iter (+/- 5,441)
test bench_iter_ones_using_slice_directly_all_zero ... bench:       9,794 ns/iter (+/- 44)
```
The benchmarks from the separate file:
```
test bench_insert_range                            ... bench:       2,774 ns/iter (+/- 818)
test bench_insert_range_using_loop                 ... bench:   2,099,708 ns/iter (+/- 28,504)
test bench_iter_ones_all_ones                      ... bench:     792,420 ns/iter (+/- 5,258)
test bench_iter_ones_all_zeros                     ... bench:       9,806 ns/iter (+/- 237)
test bench_iter_ones_using_contains_all_ones       ... bench:     523,329 ns/iter (+/- 4,939)
test bench_iter_ones_using_contains_all_zeros      ... bench:     523,483 ns/iter (+/- 9,619)
test bench_iter_ones_using_slice_directly_all_ones ... bench:     367,465 ns/iter (+/- 3,741)
test bench_iter_ones_using_slice_directly_all_zero ... bench:       9,859 ns/iter (+/- 92)
```

Given this I'm going to close this issue.
