### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by shuoli84** [petgraph/fixedbitset#93]
There are eight new commits since last release. Thanks in advance.

**Comment by james7132** [comment]
There is one thing I think needs to be addressed following #74: usize is dependent on the architecture and is used in the serde implementation. I'd like to get that sorted out before anything public is released.

**Comment by shuoli84** [comment]
> There is one thing I think needs to be addressed following #74: usize is dependent on the architecture and is used in the serde implementation. I'd like to get that sorted out before anything public is released.

I see. You mean the serialized data is incompatible before and after the u32 -> usize change, right?

**Comment by james7132** [comment]
That's true, but I'm more concerned with portability of serialized data from one architecture to another.

**Comment by shuoli84** [comment]
yes, need to create custom serialize mod which also makes endianness correct.

**Comment by shuoli84** [comment]
Current implementation is not portable, maybe we should define the serialized format first. add an endian flag to the data, or serialize data to [u8]?

**Comment by shuoli84** [comment]
@james7132 if this is a release blocker, how about hide the usize as a opt in feature?

**Comment by james7132** [comment]
0.5.0 has been published.
